# Generated by Django 5.0.1 on 2024-02-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmberAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_info', models.TextField()),
                ('vechile_LP', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'AmberAlert',
            },
        ),
    ]
