# Generated by Django 5.0.1 on 2024-02-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtxapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amberalert',
            name='alert_lat',
            field=models.CharField(default='28.0587 N', max_length=10),
        ),
        migrations.AddField(
            model_name='amberalert',
            name='alert_long',
            field=models.CharField(default='82.4139 W', max_length=10),
        ),
    ]
