# Generated by Django 5.0.1 on 2024-02-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtxapi', '0002_amberalert_alert_lat_amberalert_alert_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amberalert',
            old_name='vechile_LP',
            new_name='vehicle_LP',
        ),
    ]
