# Generated by Django 5.0.1 on 2024-03-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtxapi', '0003_rename_vechile_lp_amberalert_vehicle_lp'),
    ]

    operations = [
        migrations.AddField(
            model_name='amberalert',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amberalert',
            name='alert_lat',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='amberalert',
            name='alert_long',
            field=models.CharField(max_length=10),
        ),
    ]
