# Generated by Django 5.0.1 on 2024-04-03 02:18

import datetime
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtxapi', '0005_userresults_alter_amberalert_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amberalert',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 22, 18, 58, 26141)),
        ),
        migrations.AlterField(
            model_name='userresults',
            name='date',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
