# Generated by Django 5.0.1 on 2024-04-19 18:02

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtxapi', '0008_alter_amberalert_date_alter_userresults_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='amberalert',
            name='recent_Interaction',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='amberalert',
            name='date',
            field=models.DateField(default=django.db.models.functions.datetime.Now),
        ),
    ]
