# Generated by Django 5.0.4 on 2024-04-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtxapi', '0009_amberalert_recent_interaction_alter_amberalert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amberalert',
            name='alert_lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amberalert',
            name='alert_long',
            field=models.CharField(max_length=100),
        ),
    ]
