# Generated by Django 5.0.4 on 2024-04-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtxapi', '0010_alter_amberalert_alert_lat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResults',
        ),
    ]
