# Generated by Django 5.0.4 on 2024-04-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtxapi', '0012_alter_amberalert_date_alter_amberalert_vehicle_lp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amberalert',
            name='vehicle_info',
            field=models.TextField(default=' '),
        ),
    ]
