# Generated by Django 5.0.4 on 2024-04-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtxapi', '0013_alter_amberalert_vehicle_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amberalert',
            name='vehicle_LP',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='amberalert',
            name='vehicle_info',
            field=models.TextField(blank=True),
        ),
    ]
