# Generated by Django 5.0.4 on 2024-04-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtxapi', '0014_alter_amberalert_vehicle_lp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amberalert',
            name='direction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
